# Site settings
title: Xiaojin Ma | 马小巾
SEOTitle: Xiaojin Ma | Personal Website
header-img: img/arthill1.jpg
email: <a href="mailto:xiaojinma@wustl.edu" target="_blank">xiaojinma_AT_wustl.edu</a>
description: ""
keyword: "Xiaojin Ma, cognitive psychology, visual attention, xiaojinma"
url: "http://xiaojin-ma.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
#github_repo: "https://github.com/qiubaiying/qiubaiying.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Department of Psychological and Brain Sciences<br/>Washington University in St. Louis<br/>"
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
#zhihu_username:     qiubaiying
#github_username:    qiubaiying
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID:                            #生成的clientID
  clientSecret:    #生成的clientSecret
  repo:     #仓库名称
  owner:    #github用户名
  admin: 
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 

# Google Analytics
ga_track_id:             # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


friends: [
    {
        title: "ResearchGate",
        href: "https://www.researchgate.net/profile/Xiaojin-Ma-2"
    },{
        title: "ORCID",
        href: "https://orcid.org/0000-0003-4592-6408"
    },{
        title: "Google Scholar",
        href: "https://scholar.google.com/citations?user=7RSpO8IAAAAJ&hl=en"
    }
]
