# Site settings
title: Xiaojin Ma | 马小巾
SEOTitle: Xiaojin Ma | Personal Website
header-img: img/shenzhen.jpg
email: <a href="mailto:xiaojinma@wustl.edu" target="_blank">xiaojinma@wustl.edu</a>
description: ""
keyword: "Xiaojin Ma, cognitive psychology, visual attention, xiaojinma"
url: "http://xiaojin-ma.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
#github_repo: "https://github.com/qiubaiying/qiubaiying.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: Hi, I'm Jin <br/>你好，我叫马小巾<br/>
sidebar-avatar: /img/avatar2.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`
links: <input type="image" src="img/scholar.png" width="30" height="30" onclick="location.href='https://scholar.google.com/citations?user=7RSpO8IAAAAJ&hl=en'" /> <input type="image" src='img/twitter.png' width="30" height="30" onclick="location.href='https://twitter.com/XiaojinMa'"> <input type="image" src='img/researchgate.png' width="30" height="30" onclick="location.href='https://www.researchgate.net/profile/Xiaojin-Ma-2'"> <input type="image" src='img/osf.png' width="30" height="30" onclick="location.href='https://osf.io/9p6jb/'"> <input type="image" src='img/linkedin.png' width="30" height="30" onclick="location.href='https://www.linkedin.com/in/xiaojin-ma-b25456bb/'"> <input type="image" src='img/ORCID.png' width="30" height="30" onclick="location.href='https://orcid.org/0000-0003-4592-6408'">
# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 

# Google Analytics
ga_track_id:             # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true
